name: Deploy docs

on:
  workflow_dispatch:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout # checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: npm install postcss-cli && hugo --minify

      - name: Setup aliyun oss
        run: wget http://gosspublic.alicdn.com/ossutil/1.7.18/ossutil64 && chmod +x ossutil64

      - name: Configure Alibaba Cloud OSSUTIL
        run: ./ossutil64 config -e oss-cn-hongkong.aliyuncs.com -i ${{ secrets.OSS_ACCESSKEYID }} -k ${{ secrets.OSS_ACCESSKEYSECRET }}

      - name: Upload the web to the chosen oss bucket
        run: ./ossutil64 cp -rf ./public/ oss://koupleless-dosc/
